version: "3"

services:
  dg_exercise_db:
    image: postgres
    container_name: dg_exercise_db
    environment:
      - POSTGRES_USER=dispatchgoods
      - POSTGRES_PASSWORD=dispatchgoods
      - POSTGRES_DB=dg_exercise
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
